// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"github.com/google/uuid"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func NewInsertAgentGuidanceParams(
	researchbriefid string,
	guidancekey string,
	guidancevalue string,
) InsertAgentGuidanceParams {
	return InsertAgentGuidanceParams{
		ID:              uuid.New().String(),
		ResearchBriefID: researchbriefid,
		GuidanceKey:     guidancekey,
		GuidanceValue:   guidancevalue,
	}
}

func NewUpdateAgentGuidanceParams(
	id string,
	researchbriefid string,
	guidancekey string,
	guidancevalue string,
) UpdateAgentGuidanceParams {
	return UpdateAgentGuidanceParams{
		ID:              id,
		ResearchBriefID: researchbriefid,
		GuidanceKey:     guidancekey,
		GuidanceValue:   guidancevalue,
	}
}

func NewQueryPaginatedAgentGuidancesParams(limit, offset int64) QueryPaginatedAgentGuidancesParams {
	return QueryPaginatedAgentGuidancesParams{
		Limit:  limit,
		Offset: offset,
	}
}
