// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"github.com/google/uuid"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func NewInsertCompanyCandidatesParams(
	researchbriefid string,
	name string,
	domain string,
	description string,
	industry string,
	location string,
) InsertCompanyCandidatesParams {
	return InsertCompanyCandidatesParams{
		ID:              uuid.New().String(),
		ResearchBriefID: researchbriefid,
		Name:            name,
		Domain:          domain,
		Description:     description,
		Industry:        industry,
		Location:        location,
	}
}

func NewUpdateCompanyCandidatesParams(
	id string,
	researchbriefid string,
	name string,
	domain string,
	description string,
	industry string,
	location string,
) UpdateCompanyCandidatesParams {
	return UpdateCompanyCandidatesParams{
		ID:              id,
		ResearchBriefID: researchbriefid,
		Name:            name,
		Domain:          domain,
		Description:     description,
		Industry:        industry,
		Location:        location,
	}
}

func NewQueryPaginatedCompanyCandidatessParams(limit, offset int64) QueryPaginatedCompanyCandidatessParams {
	return QueryPaginatedCompanyCandidatessParams{
		Limit:  limit,
		Offset: offset,
	}
}
