// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Agentguidance struct {
	ID              string
	ResearchBriefID string
	GuidanceKey     string
	GuidanceValue   string
}

type Companycandidate struct {
	ID              string
	ResearchBriefID string
	Name            string
	Domain          string
	Description     string
	Industry        string
	Location        string
}

type Researchbrief struct {
	ID                   string
	IdentificationStatus string
	CompanyName          string
	OfficialDomain       string
	Headquarters         string
	Industry             string
	CompanyType          string
	Status               string
	GeographicScope      string
	ResearchDepth        string
	ConfidenceScore      float64
	LastUpdated          time.Time
}

type Source struct {
	ID              string
	ResearchBriefID string
	SourceUrl       string
}

type Specialconsideration struct {
	ID              string
	ResearchBriefID string
	Consideration   string
}
