// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"github.com/google/uuid"
	"time"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func NewInsertResearchBriefParams(
	identificationstatus string,
	companyname string,
	officialdomain string,
	headquarters string,
	industry string,
	companytype string,
	status string,
	geographicscope string,
	researchdepth string,
	confidencescore float64,
	lastupdated time.Time,
) InsertResearchBriefParams {
	return InsertResearchBriefParams{
		ID:                   uuid.New().String(),
		IdentificationStatus: identificationstatus,
		CompanyName:          companyname,
		OfficialDomain:       officialdomain,
		Headquarters:         headquarters,
		Industry:             industry,
		CompanyType:          companytype,
		Status:               status,
		GeographicScope:      geographicscope,
		ResearchDepth:        researchdepth,
		ConfidenceScore:      confidencescore,
		LastUpdated:          lastupdated,
	}
}

func NewUpdateResearchBriefParams(
	id string,
	identificationstatus string,
	companyname string,
	officialdomain string,
	headquarters string,
	industry string,
	companytype string,
	status string,
	geographicscope string,
	researchdepth string,
	confidencescore float64,
	lastupdated time.Time,
) UpdateResearchBriefParams {
	return UpdateResearchBriefParams{
		ID:                   id,
		IdentificationStatus: identificationstatus,
		CompanyName:          companyname,
		OfficialDomain:       officialdomain,
		Headquarters:         headquarters,
		Industry:             industry,
		CompanyType:          companytype,
		Status:               status,
		GeographicScope:      geographicscope,
		ResearchDepth:        researchdepth,
		ConfidenceScore:      confidencescore,
		LastUpdated:          lastupdated,
	}
}

func NewQueryPaginatedResearchBriefsParams(limit, offset int64) QueryPaginatedResearchBriefsParams {
	return QueryPaginatedResearchBriefsParams{
		Limit:  limit,
		Offset: offset,
	}
}
