// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"github.com/google/uuid"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func NewInsertSourcesParams(
	researchbriefid string,
	sourceurl string,
) InsertSourcesParams {
	return InsertSourcesParams{
		ID:              uuid.New().String(),
		ResearchBriefID: researchbriefid,
		SourceUrl:       sourceurl,
	}
}

func NewUpdateSourcesParams(
	id string,
	researchbriefid string,
	sourceurl string,
) UpdateSourcesParams {
	return UpdateSourcesParams{
		ID:              id,
		ResearchBriefID: researchbriefid,
		SourceUrl:       sourceurl,
	}
}

func NewQueryPaginatedSourcessParams(limit, offset int64) QueryPaginatedSourcessParams {
	return QueryPaginatedSourcessParams{
		Limit:  limit,
		Offset: offset,
	}
}
