// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"github.com/google/uuid"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func NewInsertSpecialConsiderationsParams(
	researchbriefid string,
	consideration string,
) InsertSpecialConsiderationsParams {
	return InsertSpecialConsiderationsParams{
		ID:              uuid.New().String(),
		ResearchBriefID: researchbriefid,
		Consideration:   consideration,
	}
}

func NewUpdateSpecialConsiderationsParams(
	id string,
	researchbriefid string,
	consideration string,
) UpdateSpecialConsiderationsParams {
	return UpdateSpecialConsiderationsParams{
		ID:              id,
		ResearchBriefID: researchbriefid,
		Consideration:   consideration,
	}
}

func NewQueryPaginatedSpecialConsiderationssParams(limit, offset int64) QueryPaginatedSpecialConsiderationssParams {
	return QueryPaginatedSpecialConsiderationssParams{
		Limit:  limit,
		Offset: offset,
	}
}
